version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tortilla
    ports:
    - "3336:3306"
    volumes:
    - db-data:/var/lib/mysql
  python:
    image: python:3.8
    ports:
    - "9900:5000"
    depends_on:
    - db
    volumes:
    - .:/code
    environment:
      DATABASE_URL: mysql://root:my-secret-pw@db:3336/my_database

volumes:
  db-data: